### PR TITLE
Snapshot version fix

### PR DESCRIPTION
**Pull request by malchmih**

### CODE REVIEW

**Comment by fehmicansaglam** [comment]
Thanks!

**Comment by malchmih** [comment]
You are welcome =) Really looking forward to start using it with Play! Do you have any (even very rough) estimate for this?

**Comment by fehmicansaglam** [comment]
I think it is already usable in any application right now. But before using Tepkin in production I suggest waiting for Akka Streams 1.0 to be finalized which is expected to happen in 2 months.

**Comment by malchmih** [comment]
Ok, thanks! Do you play to add something like https://github.com/fehmicansaglam/reactivemongo-extensions ?

**Comment by fehmicansaglam** [comment]
Yes. Tepkin MongoCollection has already borrowed some ideas(APIs) from RME like count, findOne, etc. I am not sure about DAO classes but I plan to provide JSON support, case class serialization/deserialization and maybe some more features.

**Comment by malchmih** [comment]
Great!

**Pull request merged**
